Meteor.startup(function() {
  if (Meteor.users.find({
      roles: 'guide'
    }).count() === 0) {
    var guides = [{
      "gender": "Female",
      "firstName": "Tina",
      "lastName": "Jones",
      "email": "tjones0@sogou.com",
      "country": "China",
      "dob": "8/28/1969",
      "rate": "100.28"
    }, {
      "gender": "Female",
      "firstName": "Frances",
      "lastName": "Alexander",
      "email": "falexander1@walmart.com",
      "country": "France",
      "dob": "8/31/1974",
      "rate": "125.05"
    }, {
      "gender": "Male",
      "firstName": "Billy",
      "lastName": "Cox",
      "email": "bcox2@hostgator.com",
      "country": "Russia",
      "dob": "4/21/1978",
      "rate": "148.00"
    }, {
      "gender": "Female",
      "firstName": "Nicole",
      "lastName": "Williamson",
      "email": "nwilliamson3@npr.org",
      "country": "Philippines",
      "dob": "7/6/1961",
      "rate": "103.83"
    }, {
      "gender": "Female",
      "firstName": "Mary",
      "lastName": "Perkins",
      "email": "mperkins4@gov.uk",
      "country": "Senegal",
      "dob": "3/30/1974",
      "rate": "185.54"
    }, {
      "gender": "Male",
      "firstName": "Ronald",
      "lastName": "Oliver",
      "email": "roliver5@google.cn",
      "country": "Mongolia",
      "dob": "8/9/1964",
      "rate": "164.49"
    }, {
      "gender": "Male",
      "firstName": "Joe",
      "lastName": "Dixon",
      "email": "jdixon6@wikia.com",
      "country": "China",
      "dob": "2/14/1997",
      "rate": "161.64"
    }, {
      "gender": "Female",
      "firstName": "Tina",
      "lastName": "Sullivan",
      "email": "tsullivan7@patch.com",
      "country": "Brazil",
      "dob": "9/13/1994",
      "rate": "161.89"
    }, {
      "gender": "Female",
      "firstName": "Angela",
      "lastName": "Gutierrez",
      "email": "agutierrez8@illinois.edu",
      "country": "Kyrgyzstan",
      "dob": "8/11/1990",
      "rate": "190.55"
    }, {
      "gender": "Female",
      "firstName": "Jessica",
      "lastName": "Torres",
      "email": "jtorres9@hugedomains.com",
      "country": "Armenia",
      "dob": "5/28/1977",
      "rate": "131.47"
    }, {
      "gender": "Female",
      "firstName": "Phyllis",
      "lastName": "Jones",
      "email": "pjonesa@hao123.com",
      "country": "Ukraine",
      "dob": "11/4/1983",
      "rate": "108.73"
    }, {
      "gender": "Male",
      "firstName": "Arthur",
      "lastName": "Willis",
      "email": "awillisb@who.int",
      "country": "Russia",
      "dob": "12/9/1990",
      "rate": "105.94"
    }, {
      "gender": "Male",
      "firstName": "Thomas",
      "lastName": "Torres",
      "email": "ttorresc@eepurl.com",
      "country": "Indonesia",
      "dob": "5/29/1974",
      "rate": "140.72"
    }, {
      "gender": "Female",
      "firstName": "Cynthia",
      "lastName": "James",
      "email": "cjamesd@gov.uk",
      "country": "Luxembourg",
      "dob": "8/12/1966",
      "rate": "197.94"
    }, {
      "gender": "Female",
      "firstName": "Shirley",
      "lastName": "Flores",
      "email": "sflorese@pbs.org",
      "country": "Indonesia",
      "dob": "1/23/1974",
      "rate": "160.79"
    }, {
      "gender": "Female",
      "firstName": "Martha",
      "lastName": "Hayes",
      "email": "mhayesf@wordpress.com",
      "country": "South Korea",
      "dob": "10/9/1981",
      "rate": "108.45"
    }, {
      "gender": "Male",
      "firstName": "Richard",
      "lastName": "Hunter",
      "email": "rhunterg@wufoo.com",
      "country": "Greece",
      "dob": "8/18/1986",
      "rate": "156.68"
    }, {
      "gender": "Male",
      "firstName": "Ernest",
      "lastName": "Romero",
      "email": "eromeroh@arizona.edu",
      "country": "China",
      "dob": "6/6/1986",
      "rate": "134.31"
    }, {
      "gender": "Male",
      "firstName": "Roger",
      "lastName": "Porter",
      "email": "rporteri@tmall.com",
      "country": "Russia",
      "dob": "7/11/1973",
      "rate": "115.68"
    }, {
      "gender": "Male",
      "firstName": "Dennis",
      "lastName": "Edwards",
      "email": "dedwardsj@answers.com",
      "country": "Finland",
      "dob": "9/29/1997",
      "rate": "171.59"
    }, {
      "gender": "Female",
      "firstName": "Kathy",
      "lastName": "Henderson",
      "email": "khendersonk@time.com",
      "country": "Poland",
      "dob": "12/26/1988",
      "rate": "167.58"
    }, {
      "gender": "Female",
      "firstName": "Phyllis",
      "lastName": "Ryan",
      "email": "pryanl@skype.com",
      "country": "Russia",
      "dob": "4/8/1997",
      "rate": "148.72"
    }, {
      "gender": "Female",
      "firstName": "Robin",
      "lastName": "Payne",
      "email": "rpaynem@mlb.com",
      "country": "Indonesia",
      "dob": "6/21/1977",
      "rate": "149.00"
    }, {
      "gender": "Male",
      "firstName": "James",
      "lastName": "Franklin",
      "email": "jfranklinn@soundcloud.com",
      "country": "Indonesia",
      "dob": "5/6/1987",
      "rate": "196.78"
    }, {
      "gender": "Male",
      "firstName": "David",
      "lastName": "Rodriguez",
      "email": "drodriguezo@mozilla.org",
      "country": "Slovenia",
      "dob": "9/11/1961",
      "rate": "162.54"
    }, {
      "gender": "Female",
      "firstName": "Jessica",
      "lastName": "Stephens",
      "email": "jstephensp@ebay.com",
      "country": "China",
      "dob": "8/18/1993",
      "rate": "140.37"
    }, {
      "gender": "Male",
      "firstName": "Albert",
      "lastName": "Riley",
      "email": "arileyq@reddit.com",
      "country": "Indonesia",
      "dob": "10/15/1985",
      "rate": "187.81"
    }, {
      "gender": "Male",
      "firstName": "Carlos",
      "lastName": "Reyes",
      "email": "creyesr@disqus.com",
      "country": "Russia",
      "dob": "7/27/1968",
      "rate": "116.10"
    }, {
      "gender": "Male",
      "firstName": "Randy",
      "lastName": "Boyd",
      "email": "rboyds@1688.com",
      "country": "Portugal",
      "dob": "6/9/1975",
      "rate": "164.76"
    }, {
      "gender": "Female",
      "firstName": "Julie",
      "lastName": "Gibson",
      "email": "jgibsont@facebook.com",
      "country": "Indonesia",
      "dob": "12/13/1968",
      "rate": "121.62"
    }, {
      "gender": "Male",
      "firstName": "Willie",
      "lastName": "Morris",
      "email": "wmorrisu@qq.com",
      "country": "Serbia",
      "dob": "5/31/1964",
      "rate": "139.02"
    }, {
      "gender": "Male",
      "firstName": "Todd",
      "lastName": "Wagner",
      "email": "twagnerv@geocities.com",
      "country": "China",
      "dob": "1/23/1981",
      "rate": "183.41"
    }, {
      "gender": "Female",
      "firstName": "Norma",
      "lastName": "Rogers",
      "email": "nrogersw@51.la",
      "country": "Zambia",
      "dob": "6/22/1975",
      "rate": "108.98"
    }, {
      "gender": "Female",
      "firstName": "Frances",
      "lastName": "Pierce",
      "email": "fpiercex@etsy.com",
      "country": "United States",
      "dob": "7/13/1989",
      "rate": "182.13"
    }, {
      "gender": "Female",
      "firstName": "Cheryl",
      "lastName": "Bryant",
      "email": "cbryanty@4shared.com",
      "country": "Somalia",
      "dob": "7/6/1990",
      "rate": "167.86"
    }, {
      "gender": "Female",
      "firstName": "Marilyn",
      "lastName": "Dixon",
      "email": "mdixonz@joomla.org",
      "country": "Thailand",
      "dob": "3/23/1981",
      "rate": "127.58"
    }, {
      "gender": "Male",
      "firstName": "Kevin",
      "lastName": "Washington",
      "email": "kwashington10@nifty.com",
      "country": "Sweden",
      "dob": "7/1/1968",
      "rate": "108.74"
    }, {
      "gender": "Male",
      "firstName": "Frank",
      "lastName": "Butler",
      "email": "fbutler11@phpbb.com",
      "country": "Indonesia",
      "dob": "10/8/1970",
      "rate": "119.82"
    }, {
      "gender": "Male",
      "firstName": "James",
      "lastName": "Peterson",
      "email": "jpeterson12@boston.com",
      "country": "Poland",
      "dob": "8/28/1966",
      "rate": "138.82"
    }, {
      "gender": "Female",
      "firstName": "Julie",
      "lastName": "Martinez",
      "email": "jmartinez13@fc2.com",
      "country": "South Africa",
      "dob": "11/28/1981",
      "rate": "118.53"
    }, {
      "gender": "Male",
      "firstName": "Edward",
      "lastName": "Weaver",
      "email": "eweaver14@examiner.com",
      "country": "Indonesia",
      "dob": "5/1/1964",
      "rate": "147.18"
    }, {
      "gender": "Male",
      "firstName": "Fred",
      "lastName": "Harris",
      "email": "fharris15@ocn.ne.jp",
      "country": "Russia",
      "dob": "4/30/1968",
      "rate": "151.65"
    }, {
      "gender": "Male",
      "firstName": "Philip",
      "lastName": "Medina",
      "email": "pmedina16@nasa.gov",
      "country": "China",
      "dob": "7/2/1982",
      "rate": "180.27"
    }, {
      "gender": "Female",
      "firstName": "Joan",
      "lastName": "Morales",
      "email": "jmorales17@cbsnews.com",
      "country": "China",
      "dob": "8/31/1961",
      "rate": "155.13"
    }, {
      "gender": "Male",
      "firstName": "Larry",
      "lastName": "Arnold",
      "email": "larnold18@ebay.co.uk",
      "country": "China",
      "dob": "4/13/1961",
      "rate": "181.92"
    }, {
      "gender": "Male",
      "firstName": "Joe",
      "lastName": "Alvarez",
      "email": "jalvarez19@disqus.com",
      "country": "Costa Rica",
      "dob": "5/17/1967",
      "rate": "137.57"
    }, {
      "gender": "Female",
      "firstName": "Julia",
      "lastName": "Long",
      "email": "jlong1a@smh.com.au",
      "country": "China",
      "dob": "10/27/1975",
      "rate": "116.43"
    }, {
      "gender": "Male",
      "firstName": "Joe",
      "lastName": "Snyder",
      "email": "jsnyder1b@cnbc.com",
      "country": "Indonesia",
      "dob": "11/6/1980",
      "rate": "105.85"
    }, {
      "gender": "Male",
      "firstName": "Bobby",
      "lastName": "Simmons",
      "email": "bsimmons1c@soundcloud.com",
      "country": "Uganda",
      "dob": "4/30/1993",
      "rate": "178.16"
    }, {
      "gender": "Male",
      "firstName": "Roger",
      "lastName": "Hawkins",
      "email": "rhawkins1d@dell.com",
      "country": "Togo",
      "dob": "9/12/1997",
      "rate": "146.77"
    }, {
      "gender": "Female",
      "firstName": "Ann",
      "lastName": "Ramos",
      "email": "aramos1e@amazonaws.com",
      "country": "China",
      "dob": "9/3/1965",
      "rate": "138.52"
    }, {
      "gender": "Male",
      "firstName": "Billy",
      "lastName": "Hicks",
      "email": "bhicks1f@cpanel.net",
      "country": "Portugal",
      "dob": "12/27/1987",
      "rate": "194.68"
    }, {
      "gender": "Male",
      "firstName": "Anthony",
      "lastName": "Larson",
      "email": "alarson1g@infoseek.co.jp",
      "country": "Philippines",
      "dob": "9/11/1992",
      "rate": "193.50"
    }, {
      "gender": "Male",
      "firstName": "Benjamin",
      "lastName": "Watkins",
      "email": "bwatkins1h@cafepress.com",
      "country": "Portugal",
      "dob": "5/9/1976",
      "rate": "182.81"
    }, {
      "gender": "Male",
      "firstName": "Jonathan",
      "lastName": "Gutierrez",
      "email": "jgutierrez1i@sbwire.com",
      "country": "Greece",
      "dob": "4/18/1979",
      "rate": "107.41"
    }, {
      "gender": "Female",
      "firstName": "Jacqueline",
      "lastName": "Crawford",
      "email": "jcrawford1j@dailymotion.com",
      "country": "Ghana",
      "dob": "4/11/1977",
      "rate": "146.02"
    }, {
      "gender": "Female",
      "firstName": "Sandra",
      "lastName": "Torres",
      "email": "storres1k@gizmodo.com",
      "country": "Egypt",
      "dob": "11/19/1992",
      "rate": "129.44"
    }, {
      "gender": "Male",
      "firstName": "Aaron",
      "lastName": "Black",
      "email": "ablack1l@prnewswire.com",
      "country": "Poland",
      "dob": "11/6/1974",
      "rate": "127.17"
    }, {
      "gender": "Male",
      "firstName": "Albert",
      "lastName": "Wilson",
      "email": "awilson1m@howstuffworks.com",
      "country": "Egypt",
      "dob": "12/7/1975",
      "rate": "142.41"
    }, {
      "gender": "Female",
      "firstName": "Carol",
      "lastName": "Cruz",
      "email": "ccruz1n@slashdot.org",
      "country": "Argentina",
      "dob": "9/8/1974",
      "rate": "103.26"
    }, {
      "gender": "Male",
      "firstName": "Walter",
      "lastName": "Rodriguez",
      "email": "wrodriguez1o@cocolog-nifty.com",
      "country": "Canada",
      "dob": "6/6/1966",
      "rate": "100.69"
    }, {
      "gender": "Female",
      "firstName": "Joyce",
      "lastName": "Carter",
      "email": "jcarter1p@java.com",
      "country": "Benin",
      "dob": "3/13/1978",
      "rate": "136.04"
    }, {
      "gender": "Male",
      "firstName": "Timothy",
      "lastName": "Cunningham",
      "email": "tcunningham1q@dyndns.org",
      "country": "Indonesia",
      "dob": "10/23/1982",
      "rate": "194.89"
    }, {
      "gender": "Female",
      "firstName": "Irene",
      "lastName": "Arnold",
      "email": "iarnold1r@gmpg.org",
      "country": "Philippines",
      "dob": "12/29/1995",
      "rate": "126.28"
    }, {
      "gender": "Female",
      "firstName": "Rose",
      "lastName": "Ferguson",
      "email": "rferguson1s@cbc.ca",
      "country": "Philippines",
      "dob": "6/20/1963",
      "rate": "184.07"
    }, {
      "gender": "Male",
      "firstName": "John",
      "lastName": "Wallace",
      "email": "jwallace1t@wikipedia.org",
      "country": "Sweden",
      "dob": "8/9/1997",
      "rate": "167.49"
    }, {
      "gender": "Female",
      "firstName": "Janet",
      "lastName": "Gutierrez",
      "email": "jgutierrez1u@blinklist.com",
      "country": "Honduras",
      "dob": "10/10/1964",
      "rate": "151.23"
    }, {
      "gender": "Male",
      "firstName": "Wayne",
      "lastName": "Dixon",
      "email": "wdixon1v@alexa.com",
      "country": "Philippines",
      "dob": "10/2/1971",
      "rate": "193.11"
    }, {
      "gender": "Male",
      "firstName": "Ralph",
      "lastName": "Williams",
      "email": "rwilliams1w@oakley.com",
      "country": "China",
      "dob": "2/5/1990",
      "rate": "130.61"
    }, {
      "gender": "Male",
      "firstName": "Wayne",
      "lastName": "Graham",
      "email": "wgraham1x@bbc.co.uk",
      "country": "China",
      "dob": "2/6/1995",
      "rate": "197.43"
    }, {
      "gender": "Female",
      "firstName": "Judy",
      "lastName": "Jacobs",
      "email": "jjacobs1y@slashdot.org",
      "country": "Chile",
      "dob": "4/9/1997",
      "rate": "193.41"
    }, {
      "gender": "Female",
      "firstName": "Rebecca",
      "lastName": "Gutierrez",
      "email": "rgutierrez1z@mozilla.org",
      "country": "Japan",
      "dob": "7/8/1969",
      "rate": "172.92"
    }, {
      "gender": "Male",
      "firstName": "Shawn",
      "lastName": "Alexander",
      "email": "salexander20@topsy.com",
      "country": "United States",
      "dob": "9/19/1979",
      "rate": "114.62"
    }, {
      "gender": "Female",
      "firstName": "Louise",
      "lastName": "Mitchell",
      "email": "lmitchell21@typepad.com",
      "country": "Indonesia",
      "dob": "4/2/1979",
      "rate": "157.27"
    }, {
      "gender": "Male",
      "firstName": "John",
      "lastName": "Jordan",
      "email": "jjordan22@zdnet.com",
      "country": "Burkina Faso",
      "dob": "12/14/1993",
      "rate": "110.39"
    }, {
      "gender": "Female",
      "firstName": "Susan",
      "lastName": "Andrews",
      "email": "sandrews23@creativecommons.org",
      "country": "China",
      "dob": "5/12/1973",
      "rate": "186.73"
    }, {
      "gender": "Male",
      "firstName": "Jeremy",
      "lastName": "Webb",
      "email": "jwebb24@wikispaces.com",
      "country": "Indonesia",
      "dob": "5/13/1961",
      "rate": "110.47"
    }, {
      "gender": "Female",
      "firstName": "Doris",
      "lastName": "Ruiz",
      "email": "druiz25@moonfruit.com",
      "country": "Argentina",
      "dob": "6/9/1963",
      "rate": "179.11"
    }, {
      "gender": "Male",
      "firstName": "Ryan",
      "lastName": "Knight",
      "email": "rknight26@gravatar.com",
      "country": "Botswana",
      "dob": "2/27/1967",
      "rate": "157.67"
    }, {
      "gender": "Female",
      "firstName": "Kelly",
      "lastName": "Webb",
      "email": "kwebb27@opera.com",
      "country": "Benin",
      "dob": "4/20/1963",
      "rate": "151.37"
    }, {
      "gender": "Male",
      "firstName": "Roy",
      "lastName": "Jones",
      "email": "rjones28@nyu.edu",
      "country": "Indonesia",
      "dob": "10/15/1994",
      "rate": "181.67"
    }, {
      "gender": "Female",
      "firstName": "Ruth",
      "lastName": "Young",
      "email": "ryoung29@pen.io",
      "country": "Micronesia",
      "dob": "6/16/1961",
      "rate": "180.53"
    }, {
      "gender": "Male",
      "firstName": "Keith",
      "lastName": "Martin",
      "email": "kmartin2a@nba.com",
      "country": "Afghanistan",
      "dob": "1/1/1988",
      "rate": "183.01"
    }, {
      "gender": "Male",
      "firstName": "Jesse",
      "lastName": "Reid",
      "email": "jreid2b@sakura.ne.jp",
      "country": "Canada",
      "dob": "6/18/1981",
      "rate": "191.13"
    }, {
      "gender": "Female",
      "firstName": "Alice",
      "lastName": "Turner",
      "email": "aturner2c@cbc.ca",
      "country": "Poland",
      "dob": "2/17/1965",
      "rate": "131.37"
    }, {
      "gender": "Female",
      "firstName": "Kelly",
      "lastName": "Wilson",
      "email": "kwilson2d@howstuffworks.com",
      "country": "Portugal",
      "dob": "1/29/1977",
      "rate": "169.90"
    }, {
      "gender": "Male",
      "firstName": "Benjamin",
      "lastName": "Rice",
      "email": "brice2e@skyrock.com",
      "country": "Indonesia",
      "dob": "4/17/1978",
      "rate": "155.55"
    }, {
      "gender": "Female",
      "firstName": "Virginia",
      "lastName": "Reyes",
      "email": "vreyes2f@virginia.edu",
      "country": "Russia",
      "dob": "3/26/1967",
      "rate": "142.60"
    }, {
      "gender": "Male",
      "firstName": "Gerald",
      "lastName": "Montgomery",
      "email": "gmontgomery2g@wix.com",
      "country": "Indonesia",
      "dob": "5/24/1997",
      "rate": "143.68"
    }, {
      "gender": "Male",
      "firstName": "Raymond",
      "lastName": "Gutierrez",
      "email": "rgutierrez2h@123-reg.co.uk",
      "country": "Brazil",
      "dob": "6/22/1970",
      "rate": "107.02"
    }, {
      "gender": "Female",
      "firstName": "Margaret",
      "lastName": "Freeman",
      "email": "mfreeman2i@ezinearticles.com",
      "country": "Russia",
      "dob": "9/28/1988",
      "rate": "172.87"
    }, {
      "gender": "Female",
      "firstName": "Emily",
      "lastName": "Bryant",
      "email": "ebryant2j@irs.gov",
      "country": "Spain",
      "dob": "10/2/1995",
      "rate": "132.38"
    }, {
      "gender": "Female",
      "firstName": "Mildred",
      "lastName": "Fernandez",
      "email": "mfernandez2k@imgur.com",
      "country": "Philippines",
      "dob": "1/14/1993",
      "rate": "167.55"
    }, {
      "gender": "Male",
      "firstName": "Clarence",
      "lastName": "Little",
      "email": "clittle2l@addtoany.com",
      "country": "Poland",
      "dob": "11/5/1983",
      "rate": "121.53"
    }, {
      "gender": "Female",
      "firstName": "Deborah",
      "lastName": "Nichols",
      "email": "dnichols2m@sina.com.cn",
      "country": "Ukraine",
      "dob": "7/11/1971",
      "rate": "138.37"
    }, {
      "gender": "Male",
      "firstName": "Donald",
      "lastName": "Wood",
      "email": "dwood2n@prlog.org",
      "country": "Ecuador",
      "dob": "8/3/1973",
      "rate": "134.65"
    }, {
      "gender": "Female",
      "firstName": "Brenda",
      "lastName": "Sanders",
      "email": "bsanders2o@economist.com",
      "country": "Belize",
      "dob": "12/19/1984",
      "rate": "130.34"
    }, {
      "gender": "Female",
      "firstName": "Deborah",
      "lastName": "Butler",
      "email": "dbutler2p@tumblr.com",
      "country": "Ethiopia",
      "dob": "8/3/1989",
      "rate": "130.85"
    }, {
      "gender": "Female",
      "firstName": "Carolyn",
      "lastName": "Harper",
      "email": "charper2q@com.com",
      "country": "Philippines",
      "dob": "2/11/1970",
      "rate": "180.15"
    }, {
      "gender": "Male",
      "firstName": "David",
      "lastName": "Stephens",
      "email": "dstephens2r@wikimedia.org",
      "country": "Morocco",
      "dob": "8/18/1984",
      "rate": "176.39"
    }];

    var days = ['sun', 'mon', 'tue', 'wed', 'thu', 'fri', 'sat'];
    var facilities = ['car', 'truck', 'van'];
    guides.forEach(function(guide) {
      guide.roles = ['guide'];
      guide.workTime = getRandomArrayElements(days, Math.floor(Math.random() * 7) + 1);
      guide.facilities = getRandomArrayElements(facilities, Math.floor(Math.random() * 3) + 1);
      guide.createdAt = new Date();
      Meteor.users.insert(guide);
    });
  }

  function getRandomArrayElements(arr, count) {
    var shuffled = arr.slice(0),
      i = arr.length,
      min = i - count,
      temp, index;
    while (i-- > min) {
      index = Math.floor((i + 1) * Math.random());
      temp = shuffled[index];
      shuffled[index] = shuffled[i];
      shuffled[i] = temp;
    }
    return shuffled.slice(min);
  }
});
